[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  included_files = [
    "node_modules/**",
    "views/**"
  ]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200